import type { Config } from 'tailwindcss';

export default {
  content: ['./app/**/*.{js,jsx,ts,tsx}'],

  theme: {
    fontSize: {
      h1: '42px',
      h2: '35px',
      h3: '29px',
      h4: '24px',
      title1: '20px',
      title2: '17px',
      body: '14px',
      caption: '12px',
    },

    colors: {
      primary: {
        light: '#f1effa',
        lightHover: '#eae6f8',
        lightActive: '#d4ccf0',
        normal: '#755bd0',
        normalHover: '#6952bb',
        normalActive: '#5e49a6',
        dark: '#58449c',
        darkHover: '#46377d',
        darkActive: '#35295e',
        darker: '#292049',
      },
      accent: {
        light: '#fffae9',
        lighHover: '#f1effa',
        lightActive: '#fff0ba',
        normal: '#ffce1f',
        normalHover: '#e6b91c',
        normalActive: '#cca519',
        dark: '#bf9b17',
        darkHover: '#997c13',
        darkActive: '#735d0e',
        darker: '#59480b',
      },
      error: {
        light: '#fae9e9',
        lighHover: '#f8dede',
        lightActive: '#f0baba',
        normal: '#ce2222',
        normalHover: '#b91f1f',
        normalActive: '#a51b1b',
        dark: '#9b1a1a',
        darkHover: '#7c1414',
        darkActive: '#5d0f0f',
        darker: '#480c0c',
      },
      succes: {
        light: '#e6f6ed',
        lightHover: '#d9f2e4',
        lightActive: '#b0e4c7',
        normal: '#00a849',
        normalHover: '#009742',
        normalActive: '#00863a',
        dark: '#007e37',
        darkHover: '#00652c',
        darkActive: '#004c21',
        darker: '#003b1a',
      },
      neutral: {
        light: '#eae9ec',
        lightHover: '#dfdee3',
        lightActive: '#bebac5',
        normal: '#2c2244',
        normalHover: '#281f3d',
        normalActive: '#231b36',
        dark: '#211a33',
        darkHover: '#1a1429',
        darkActive: '#140f1f',
        darker: '#0f0c18',
      },
    },
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
